---
- name: Demo checkmode
  hosts: servera
  tasks:
    - name: Copy a file
      ansible.builtin.copy:
        src: docs/new.txt
        dest: /home/student/new.txt
        owner: student
        group: devops

    - name: Task always in check mode
      lineinfile:
        line: "text in my file"
        dest: /home/student/new.txt
        state: present
      check_mode: yes

