---
- name: Create the directory structure where custom facts are stored
  hosts: servera
  vars:
    remote_folder: /etc/ansible/facts.d
    file: custom.fact
  tasks:
    - name: Create the directory
      ansible.builtin.file:
        state: directory
        recurse: true
        path: "{{ remote_folder }}"
    
    - name: Copy the custom fact
      ansible.builtin.copy:
        src: "{{ file }}"
        dest: "{{ remote_folder }}"

