---
- name: Use the fetch module to retrieve log files
  hosts: servera, serverb
  tasks:
    - name: Fetch the /var/log/secure log file from managed hosts
      ansible.builtin.fetch:
        src: /var/log/secure
        dest: manage-files/backup
