---
- name: Print all the facts
  hosts: servera
  gather_facts: no
  tasks:
    - name: Collect all the facts, except hardware facts
      ansible.builtin.setup:
        gather_subset:
          - 'all'
          - '!hardware'
    - ansible.builtin.debug:
       var: ansible_facts
